name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build
      run: |
        cd ./buildandreleasetask
        npm install
        cd ..

    - name: Install tfx-cli
      run: |
        npm install -g tfx-cli

    - name: Create extension
      run: |
        tfx extension create --manifest-globs vss-extension.json

    - name: Upload VSIX file
      uses: actions/upload-artifact@v2
      with:
        name: VSIX file
        path: ./*.vsix
